#!/bin/bash
mem_or_logic=$1
echo $mem_or_logic
rm list_of_blocks_test
grep -l wire ../verilog/$mem_or_logic/*.v | sed "s/\.v//g" | sed "s/verilog\/$mem_or_logic\///g" | sed "s/\.\.\///g" | sort -r | uniq  > list_of_blocks_test
file_data=$(<list_of_blocks_test)
IFS=$'\n' read -r blocklist <<< $file_data
echo $blocklist
for block in $blocklist
do
    rm ../*.oas~
    sed "s/BLOCKNAME/$block/g" /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/gamma/synthesize.tcl > /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/synthesize.tcl
    sed "s/BLOCKNAME/$block/g" /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/beta/write_output_synth.tcl > /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/write_output_synth.tcl
    sed "s/BLOCKNAME/$block/g" /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/beta/write_output_apr.tcl > /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/write_output_apr.tcl
    sed "s/BLOCKNAME/$block/g" /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/beta/place.tcl > /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/place.tcl
    sed "s/BLOCKNAME/$block/g" /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/beta/clean_oas.tcl > /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/clean_oas.tcl
    sed "s/BLOCKNAME/$block/g" /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/beta/apr.tcl > /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/apr.tcl
    rm -rf /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/VS_lib_dc
    rm -rf /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/VS_lib_icc
    cd /tmp/pdtry/sifive_u74_risc_v_core_eval_kit
    compile &
    compile_pid=$!
    echo "Synthesizing $block ..."
    while kill -0 $compile_pid ; 
    do
    	echo -n "."
        sleep 1
    done
    echo "Finished synthesis of $block"
    apr &
    apr_pid=$!
    echo "Placing and routing $block ..."
    while kill -0 $apr_pid ; 
    do
    	echo -n "."
        sleep 1
    done
    echo "Finished placement and routing of $block"
    cleanup &
    cleanup_pid=$!
    echo $cleanup_pid
    echo "Streamout/GDS Cleanup $block ..."
    while kill -0 $cleanup_pid ; 
    do
    	echo -n "."
        sleep 1
    done
    echo "Finished Streamout/GDS for $block"
    cd /tmp/pdtry/sifive_u74_risc_v_core_eval_kit/gamma;
done
